// Generated by CoffeeScript 1.7.1
(function() {
  if (!Array.prototype.every) {
    Array.prototype.every = function(fun) {
      var i, len, thisp;
      len = this.length;
      if (typeof fun !== "function") {
        throw new TypeError();
      }
      thisp = arguments_[1];
      i = 0;
      while (i < len) {
        if (i in this && !fun.call(thisp, this[i], i, this)) {
          return false;
        }
        i++;
      }
      return true;
    };
  }

}).call(this);
